# Generated by Django 3.1.7 on 2021-04-24 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dutyrota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('target_audience', models.CharField(max_length=50)),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc', models.CharField(max_length=12)),
                ('birth_date', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutyrota.gender')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutyrota.title')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='routine.person')),
                ('phone_number', models.CharField(max_length=14)),
                ('department', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=64)),
            ],
            options={
                'verbose_name': 'Supervisor',
            },
            bases=('routine.person',),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='routine.person')),
                ('phone_number', models.CharField(max_length=14)),
                ('department', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=64)),
            ],
            options={
                'verbose_name': 'Teacher',
            },
            bases=('routine.person',),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('headteacher', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('website', models.CharField(blank=True, max_length=64, null=True)),
                ('facebook', models.URLField(max_length=255)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PupilProfile',
            fields=[
                ('pupil_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('parent_phone', models.CharField(max_length=15)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.grade')),
            ],
            options={
                'verbose_name': 'Pupil',
            },
        ),
        migrations.CreateModel(
            name='LeavePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_leaving', models.DateField()),
                ('time_leaving', models.TimeField()),
                ('date_back', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DutyRota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutyrota.term')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutyrota.year')),
                ('supervisors', models.ManyToManyField(related_name='_dutyrota_supervisors_+', to='routine.SupervisorProfile')),
                ('teachers', models.ManyToManyField(related_name='_dutyrota_teachers_+', to='routine.TeacherProfile')),
            ],
            options={
                'verbose_name_plural': 'Duty Rotas',
            },
        ),
    ]
