# Generated by Django 3.1.7 on 2021-04-27 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='published_date',
        ),
        migrations.AddField(
            model_name='announcement',
            name='published_date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 27, 9, 56, 21, 513610)),
            preserve_default=False,
        ),
    ]
