# Generated by Django 3.2.6 on 2021-09-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutyrota',
            name='date',
        ),
        migrations.AddField(
            model_name='dutyrota',
            name='week_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routine.week'),
            preserve_default=False,
        ),
    ]
