# Generated by Django 3.2.6 on 2021-09-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_auto_20210907_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='week_name',
        ),
        migrations.AddField(
            model_name='week',
            name='week_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
