# Generated by Django 3.2.7 on 2021-11-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_auto_20211107_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutyrota',
            name='name',
        ),
        migrations.AlterField(
            model_name='dutyrota',
            name='week_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.week', unique=True),
        ),
    ]
