# Generated by Django 3.2.7 on 2021-11-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0007_auto_20211107_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('Students', 'Students'), ('Teachers', 'Teachers'), ('Supervisors', 'Supervisors')], max_length=50),
        ),
    ]
