# Generated by Django 3.2.7 on 2021-11-09 15:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dutyrota', '0002_auto_20211107_1301'),
        ('routine', '0008_alter_announcement_target_audience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'ANNOUNCEMENT', 'verbose_name_plural': 'ANNOUNCEMENTS'},
        ),
        migrations.AlterModelOptions(
            name='dutyrota',
            options={'verbose_name': 'DUTY SCHEDULE', 'verbose_name_plural': 'DUTY SCHEDULES'},
        ),
        migrations.AlterModelOptions(
            name='pupilprofile',
            options={'verbose_name': 'PUPIL', 'verbose_name_plural': 'PUPILS'},
        ),
        migrations.AlterModelOptions(
            name='supervisorprofile',
            options={'verbose_name': 'SUPERVISOR', 'verbose_name_plural': 'SUPERVISORS'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'TEACHER', 'verbose_name_plural': 'TEACHERS'},
        ),
        migrations.AddField(
            model_name='pupilprofile',
            name='user',
            field=models.OneToOneField(default=1, help_text='To create a new username, use the Add button on the right-side of this input field.', on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Select or create a username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=models.TextField(verbose_name='Type the detailed announcement here'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Title of the announcement'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('Students', 'Students'), ('Teachers', 'Teachers'), ('Supervisors', 'Supervisors')], max_length=50, verbose_name='To whom is this announcement being sent?'),
        ),
        migrations.AlterField(
            model_name='dutyrota',
            name='supervisors',
            field=models.ManyToManyField(related_name='_routine_dutyrota_supervisors_+', to='routine.SupervisorProfile', verbose_name='Select Supervisors who will be on duty'),
        ),
        migrations.AlterField(
            model_name='dutyrota',
            name='teachers',
            field=models.ManyToManyField(related_name='_routine_dutyrota_teachers_+', to='routine.TeacherProfile', verbose_name='Select Teachers who will be on duty'),
        ),
        migrations.AlterField(
            model_name='dutyrota',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutyrota.term', verbose_name='Select a Term for this Duty Schedule'),
        ),
        migrations.AlterField(
            model_name='dutyrota',
            name='week_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.week', unique=True, verbose_name='What Week of the term is this Duty Schedule?'),
        ),
        migrations.AlterField(
            model_name='dutyrota',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutyrota.year', verbose_name='year for this Duty Schedule'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nrc',
            field=models.CharField(max_length=12, verbose_name='Your NRC Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Upload the portrait of you face'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(help_text='To create a new username, use the Add button on the right-side of this input field.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Select or create a username'),
        ),
        migrations.AlterField(
            model_name='pupilprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(1999, 1, 1, 0, 0), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='pupilprofile',
            name='parent_phone',
            field=models.CharField(max_length=15, verbose_name='Phone number of Parents/Guadians'),
        ),
        migrations.AlterField(
            model_name='pupilprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Upload a Portrait Photo'),
        ),
        migrations.AlterField(
            model_name='pupilprofile',
            name='pupil_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name="Pupil's School ID Number"),
        ),
    ]
