# Generated by Django 3.2.9 on 2021-12-17 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routine', '0009_auto_20211109_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupilprofile',
            name='user',
            field=models.OneToOneField(help_text='To create a new username, use the Add button on the right-side of this input field.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Select or create a username for this Pupil'),
        ),
    ]
